apiVersion: v1
kind: ConfigMap
metadata:
  name: pythonhello-config
  namespace: namespace-workflow-1745470003499
  labels:
    app.kubernetes.io/name: pythonhello
    kubernetes.azure.com/generator: devhub
data: