apiVersion: v1
kind: Service
metadata:
  name: myakscluster-app
  namespace: namespace-workflow-1706750885628
spec:
  type: LoadBalancer
  selector:
    app: myakscluster-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000