apiVersion: v1
kind: Service
metadata:
  name: pythonhello
  namespace: namespace-workflow-1745470003499
  labels:
    app.kubernetes.io/name: pythonhello
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pythonhello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80