on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: sgujjaracrreg.azurecr.io
        username: ${{ secrets.acr_sgujjaracrreg_username }}
        password: ${{ secrets.acr_sgujjaracrreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sgujjaracrreg.azurecr.io/boldchickenaks:${{ github.sha }}
        docker push sgujjaracrreg.azurecr.io/boldchickenaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_boldchickenaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep test | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace test`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: test
        container-registry-url: sgujjaracrreg.azurecr.io
        container-registry-username: ${{ secrets.acr_sgujjaracrreg_username }}
        container-registry-password: ${{ secrets.acr_sgujjaracrreg_password }}
        secret-name: boldchickenadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: test
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          sgujjaracrreg.azurecr.io/boldchickenaks:${{ github.sha }}
        imagepullsecrets: |
          boldchickenadockerauth